### ISSUE TITLE
What looks good in preview does not look good in final nit-pick message

### ISSUE THREAD

**Issue by kotp** [exercism/ember-experiment#23]
![good_in_preview](https://cloud.githubusercontent.com/assets/16747/7964893/2fecda80-09e8-11e5-8f7f-c1acc1c02750.png)

Looks good in preview.

![not_so_good_in_actual_message](https://cloud.githubusercontent.com/assets/16747/7964906/3f93b058-09e8-11e5-995f-5d62cc967e29.png)

Not so good in actual message.

**Comment by kytrinyx** [comment]
Moved to https://github.com/exercism/exercism.io/issues/2413
